FROM mcr.microsoft.com/mssql/server:2019-latest

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Password123

COPY queries.sql /usr/src/app/queries.sql

# Entry point script
COPY entrypoint.sh /usr/src/app/entrypoint.sh

CMD ["bash", "/usr/src/app/entrypoint.sh"]
