FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Log_Management_Service-ArgusBackend/Log_Management_Service-ArgusBackend.csproj", "Log_Management_Service-ArgusBackend/"]
RUN dotnet restore "Log_Management_Service-ArgusBackend/Log_Management_Service-ArgusBackend.csproj"
COPY . .
WORKDIR "/src/Log_Management_Service-ArgusBackend"
RUN dotnet build "Log_Management_Service-ArgusBackend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Log_Management_Service-ArgusBackend.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Log_Management_Service-ArgusBackend.dll"]