CREATE DATABASE userdb;

CREATE TABLE userdata (
	userId VARCHAR(191) PRIMARY KEY,
	userName VARCHAR(191) NOT NULL,
	userType VARCHAR(191) NOT NULL,
	userAddress VARCHAR(191) NOT NULL,
	userTelephone VARCHAR(191) NOT NULL
);

CREATE DATABASE logdb;

CREATE TABLE logdata (
	logId VARCHAR(191) PRIMARY KEY,
	boxId VARCHAR(191) NOT NULL,
	itemType VARCHAR(191) NOT NULL,
	userId VARCHAR(191) NOT NULL,
	totalCount SERIAL NOT NULL,
	startTime TIMESTAMP NOT NULL,
	endTime TIMESTAMP NOT NULL,
	fullLogFile TEXT NOT NULL
);
