FROM mcr.microsoft.com/mssql/server:2019-latest

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Password123

COPY queries-log.sql /usr/src/app/queries-log.sql

COPY entrypoint-log.sh /usr/src/app/entrypoint-log.sh

CMD ["bash", "/usr/src/app/entrypoint-log.sh"]
